
@host=http://localhost:3000


### GET - Testes
GET {{host}}  HTTP/1.1
content-type: application/json



### POST - LOGIN  --------------------------------------------
POST {{host}}/login  HTTP/1.1
content-type: application/json

{
  "email":"thiagoteles33@gmail.com",
  "password":"quantalameira"
}

### GET  -----------------------------------------------------
GET {{host}}/jobs  HTTP/1.1
content-type: application/json


### POST  -- PAYMENT  ----------------------------------------
POST {{host}}/create  HTTP/1.1
content-type: application/json

{
  "name": "carrinho",
  "email": "Carrinho de testes",
  "password":"quanta lameira pablito"
}


### POST  -- PAYMENT  PIX  -----------------------------------
POST {{host}}/paymentpix  HTTP/1.1
content-type: application/json

{ 
  "transaction_amount": 20,
  "description": "thiagol apenas teste",
  "email": "thiagoteles@gmail.com"
}
