
@host=http://localhost:3000


### GET - Testes
GET {{host}}  HTTP/1.1
content-type: application/json

### POST - CREATE USER
POST {{host}}/create  HTTP/1.1
content-type: application/json

{
  "name":"Thiago Teles 12",
  "email":"thiagoTeles33@gmail.com",
  "password":"quantalameira"
}


### POST - Login
POST {{host}}/login  HTTP/1.1
content-type: application/json

{
  "email":"thiagoteles33@gmail.com",
  "password":"quantalameira"
}

### GET
GET {{host}}/jobs  HTTP/1.1
content-type: application/json


### POST  -- PAYMENT
POST {{host}}/create  HTTP/1.1
content-type: application/json

{
  "name": "carrinho",
  "email": "Carrinho de testes",
  "password":"quanta lameira pablito"
}